{% set name = "tapi" %}
{% set version = "1100.0.11" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: https://github.com/tpoechtrager/apple-libtapi/archive/b4f141a16c7c82f75973429c92242a8c7de3ddb1.tar.gz
    sha256: 812ab400c1226644d13fc0cd3bc93f7b3a85c715fa3ee532021d355ef916e735

build:
  number: 0
  skip: True  # [win]

requirements:
  build:
    - clang_bootstrap_osx-64  # [osx]
    - gxx_{{ target_platform }} 8.*   # [linux]
    - cmake
    - ninja
  host:
    - libcxx                  # [osx]
{% if cxx_compiler_version is defined %}
  run:
    - libcxx >={{cxx_compiler_version}}  # [osx]
{% endif %}

test:
  commands:
    - test -f $PREFIX/lib/libtapi${SHLIB_EXT}
    - test -f $PREFIX/include/tapi/tapi.h

about:
  home: https://github.com/ributzka/tapi
  license: UIUC
  license_family: MIT
  license_file:
    - tapi/LICENSE.TXT           # [osx]
    - llvm/LICENSE.TXT           # [osx]
    - LICENSE.APPLE-LIBTAPI.txt  # [linux]
    - LICENSE.LLVM.txt           # [linux]
  summary: 'TAPI is a Text-based Application Programming Interface'
  doc_url: https://opensource.apple.com/source/tapi/tapi-{{ version }}/Readme.md
  dev_url: https://github.com/ributzka/tapi

extra:
  recipe-maintainers:
    - isuruf
