{% set name = "tapi" %}
{% set version = "1100.0.11" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: https://opensource.apple.com/tarballs/tapi/tapi-{{ version }}.tar.gz  # [osx]
    sha256: 1c1d7079e65c615cb12d58c1de5c49031e56774e1f17e55a57faa5d4253b9126   # [osx]
    folder: tapi                                                               # [osx]

  - url: https://github.com/apple/swift-clang/archive/swift-4.2-branch.tar.gz  # [osx]
    sha256: 30db6f2f6ab90818393203bd95b409af73b876c1535bc4dec9f2554cf9e16387   # [osx]
    folder: clang                                                              # [osx]

  - url: https://github.com/apple/swift-llvm/archive/swift-4.2-branch.tar.gz   # [osx]
    sha256: 0cd37cce5aee48d785352a1e6ae28cc80c26b99de82910d7bd5d0476ea4c5c28   # [osx]
    folder: llvm                                                               # [osx]

  - url: https://github.com/tpoechtrager/apple-libtapi/archive/b4f141a16c7c82f75973429c92242a8c7de3ddb1.tar.gz  # [linux]
    sha256: 812ab400c1226644d13fc0cd3bc93f7b3a85c715fa3ee532021d355ef916e735   # [linux]

build:
  number: 0
  skip: True  # [win]

requirements:
  build:
    - clang_bootstrap_osx-64  # [osx]
    - {{ compiler('cxx') }}   # [linux]
    - cmake
    - ninja
  host:
    - libcxx                  # [osx]
{% if cxx_compiler_version is defined %}
  run:
    - libcxx >={{cxx_compiler_version}}  # [osx]
{% endif %}

test:
  commands:
    - test -f $PREFIX/lib/libtapi${SHLIB_EXT}
    - test -f $PREFIX/include/tapi/tapi.h

about:
  home: https://github.com/ributzka/tapi
  license: UIUC
  license_family: MIT
  license_file:
    - tapi/LICENSE.TXT           # [osx]
    - llvm/LICENSE.TXT           # [osx]
    - LICENSE.APPLE-LIBTAPI.txt  # [linux]
    - LICENSE.LLVM.txt           # [linux]
  summary: 'TAPI is a Text-based Application Programming Interface'
  doc_url: https://opensource.apple.com/source/tapi/tapi-{{ version }}/Readme.md
  dev_url: https://github.com/ributzka/tapi

extra:
  recipe-maintainers:
    - isuruf
